# Generated by Django 4.2.11 on 2024-04-17 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flan_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID del Flan')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image_url', models.URLField(verbose_name='URL de la Imagen')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('is_private', models.BooleanField(default=False, verbose_name='¿Es Privado?')),
            ],
            options={
                'verbose_name': 'Flan',
                'verbose_name_plural': 'Flanes',
            },
        ),
    ]
