# Generated by Django 4.2.11 on 2024-04-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.ImageField(null=True, upload_to='img/', verbose_name='Imagen'),
        ),
    ]
