# Generated by Django 4.2.11 on 2024-04-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_flan_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='image_url',
            field=models.ImageField(upload_to='img', verbose_name='Imagen'),
        ),
    ]
